name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        python:
        - 3.10
        grpc_version:
        - '1.54.2'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup - Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup
      id: config
      run: |
        NPROC=$(nproc)
        echo "NPROC=$NPROC" >> $GITHUB_ENV
        echo "::set-output name=NPROC::$NPROC"

    - name: Build
      uses: docker/build-push-action@v3
      id: build
      with:
        context: grpcio
        build-args: |
          python=${{ matrix.python }}
          grpc_version=-${{ matrix.grpc_version }}
          MAKEFLAGS=-j${{ steps.config.outputs.NPROC }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
